### PR TITLE
Add possibility to set at which altitude AGG should start to be updated

### PR DESCRIPTION
**Pull request by leniver**
In some case, we want to have the AGG to be able to be set at 4000m.
Instead of having to wait when we are orbiting, we can start to update the AGG when we are flying to the planet.

### CODE REVIEW

**Comment by Archaegeo** [comment]
AGG already starts to update as soon as you change the set height.  Even if you turn it off it keeps moving to the new height

**Comment by Archaegeo** [comment]
To clarify: Turn on AGG, set target altitude, turn off AGG, it will keep moving towards the target altitude.

**Comment by leniver** [comment]
Not quite true. 
If your core altitude is bigger than 200000 the AGG base altitude will not be updated.

**Comment by Archaegeo** [comment]
You can also already set target height anytime with 
/agg targetheight
in lua chat window.

**Comment by Archaegeo** [comment]
You can also already set target height anytime with
/agg targetheight
in lua chat window.

**Comment by leniver** [comment]
You are right, you can set the target AGG.

Using the /agg will only affect the target AGG variable but will not call `antigrav.setBaseAltitude`
The base altitude is only set at the end of `ap.APTick()` and if your core altitude is higher then 200000 it will wait that you approach the planet before starting to reach the target AGG.
https://github.com/Archaegeo/Archaegeo-Orbital-Hud/blob/7d105a6c228cdeea56d617b40ccf10ac76719da9/src/requires/controlclass.lua#L692
https://github.com/Archaegeo/Archaegeo-Orbital-Hud/blob/7d105a6c228cdeea56d617b40ccf10ac76719da9/src/requires/apclass.lua#L1722

**Pull request closed without merging**
